### PR TITLE
Fix build compile under kernel 5.12

### PR DESCRIPTION
**Pull request by seal331**
Due to some functions being removed from new kernels, the main tree no longer compiles cleanly, This pull request integrates my patch to rt_linux.c as well as @Tw33t3r's one about kernel 5.8. Tested on Arch Linux, kernel 5.12.15.

### CODE REVIEW

**Comment by jebwatson** [comment]
Is this still working for you? I tested it on 5.10.71-1-lts and it seems like it detects the adapter, but can't load any available networks in the wifi menu of settings.

**Comment by toddcscar-prime** [comment]
This patch worked for me on 
`
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
Linux 5.11.0-43-generic x86_64
`

**Comment by toddcscar-prime** [comment]
i got very strange behavior on this PR from github.  
When i issued the following URL to get a patch,
https://github.com/Netgear-A6210-linux-driver/Netgear-A6210/pull/26.patch
 it did not give me a correct patch file.  I had to manually save each file locally and then build.

**Comment by seal331** [comment]
I've been getting reports from the person I made this patch for the fact that the patch kind of breaks the files when applied from a clean tree instead of just using my tree but the original patch applies and works perfectly fine on my box so I have no idea where to start debugging, sorry.

**Comment by genodeftest** [comment]
Have you tried the mainline kernel's `mt76` kernel module (which should be loaded by default) instead? I guess it will provide better experience.

**Comment by genodeftest** [comment]
Closing due to inactivity.

**Pull request closed without merging**
